image: maven:latest

stages:
- build
- publish

variables:
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode --errors --fail-at-end --show-version"

cache:
  paths:
    - .m2/repository

mvn:build:
    stage: build
    script:
     - mvn $MAVEN_CLI_OPTS clean install

mvn:publish:
    stage: build
    script:
     - mvn $MAVEN_CLI_OPTS deploy
    only:
     - master