image: maven:latest

stages:
- clean
- build
- publish

variables:
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode --errors --fail-at-end --show-version"

cache:
  paths:
    - .m2/repository
    - target/

mvn:clean:
    stage: clean
    script:
     - mvn $MAVEN_CLI_OPTS clean verify
    
mvn:build:
    stage: build
    script:
     - mvn $MAVEN_CLI_OPTS clean install -U
    only:
     - master
     - develop
     - /^release\/.*$/

mvn:publish:
    stage: build
    script:
     - mvn $MAVEN_CLI_OPTS deploy -U
    only:
     - master
